const parkLib = 
{
    "Abraham Lincoln Birthplace": "abli",
    "Acadia": "acad",
    "Adams": "adam",
    "African American Civil War Memorial": "afam",
    "African Burial Ground": "afbg",
    "Agate Fossil Beds": "agfo",
    "Ala Kahakai": "alka",
    "Alagnak": "alag",
    "Alaska Public Lands": "anch",
    "Alcatraz Island": "alca",
    "Aleutian Islands World War II": "aleu",
    "Alibates Flint Quarries": "alfl",
    "Allegheny Portage Railroad": "alpo",
    "American Memorial": "amme",
    "Amistad": "amis",
    "Anacostia": "anac",
    "Andersonville": "ande",
    "Andrew Johnson": "anjo",
    "Aniakchak": "ania",
    "Antietam": "anti",
    "Apostle Islands": "apis",
    "Appalachian": "appa",
    "Appomattox Court House": "apco",
    "Arabia Mountain": "armo",
    "Arches": "arch",
    "Arkansas Post": "arpo",
    "Arlington House, The Robert  E. Lee Memorial": "arho",
    "Assateague Island": "asis",
    "Atchafalaya": "attr",
    "Augusta Canal": "auca",
    "Aztec Ruins": "azru",
    "Badlands": "badl",
    "Baltimore": "balt",
    "Baltimore-Washington": "bawa",
    "Bandelier": "band",
    "Belmont-Paul Women's Equality": "bepa",
    "Bent's Old Fort": "beol",
    "Bering Land Bridge": "bela",
    "Big Bend": "bibe",
    "Big Cypress": "bicy",
    "Big Hole": "biho",
    "Big South Fork": "biso",
    "Big Thicket": "bith",
    "Bighorn Canyon": "bica",
    "Birmingham Civil Rights": "bicr",
    "Biscayne": "bisc",
    "Black Canyon Of The Gunnison": "blca",
    "Blackstone River Valley": "blrv",
    "Blue Ridge": "blrn",
    "Blue Ridge": "blri",
    "Bluestone": "blue",
    "Booker T Washington": "bowa",
    "Boston African American": "boaf",
    "Boston Harbor Islands": "boha",
    "Boston": "bost",
    "Brices Cross Roads": "brcr",
    "Brown v. Board of Education": "brvb",
    "Bryce Canyon": "brca",
    "Buck Island Reef": "buis",
    "Buffalo": "buff",
    "Cabrillo": "cabr",
    "California": "cali",
    "Camp Nelson": "cane",
    "Canaveral": "cana",
    "Cane River Creole": "cari",
    "Cane River": "crha",
    "Canyon de Chelly": "cach",
    "Canyonlands": "cany",
    "Cape Cod": "caco",
    "Cape Hatteras": "caha",
    "Cape Henry Memorial": "came",
    "Cape Krusenstern": "cakr",
    "Cape Lookout": "calo",
    "Capitol Hill Parks": "cahi",
    "Capitol Reef": "care",
    "Captain John Smith Chesapeake": "cajo",
    "Capulin Volcano": "cavo",
    "Carl Sandburg Home": "carl",
    "Carlsbad Caverns": "cave",
    "Carter G. Woodson Home": "cawo",
    "Casa Grande Ruins": "cagr",
    "Castillo de San Marcos": "casa",
    "Castle Clinton": "cacl",
    "Castle Mountains": "camo",
    "Catoctin Mountain": "cato",
    "Cedar Breaks": "cebr",
    "Cedar Creek & Belle Grove": "cebe",
    "C\u00e9sar E. Ch\u00e1vez": "cech",
    "Chaco Culture": "chcu",
    "Chamizal": "cham",
    "Champlain Valley": "chva",
    "Channel Islands": "chis",
    "Charles Pinckney": "chpi",
    "Charles Young Buffalo Soldiers": "chyo",
    "Chattahoochee River": "chat",
    "Chesapeake & Ohio Canal": "choh",
    "Chesapeake Bay": "cbpo",
    "Chesapeake Bay Gateways and Watertrails Network": "cbgn",
    "Chickamauga & Chattanooga": "chch",
    "Chickasaw": "chic",
    "Chiricahua": "chir",
    "Christiansted": "chri",
    "City Of Rocks": "ciro",
    "Civil War Defenses of Washington": "cwdw",
    "Clara Barton": "clba",
    "Coal": "coal",
    "Colonial": "colo",
    "Colorado": "colm",
    "Coltsville": "colt",
    "Congaree": "cong",
    "Constitution Gardens": "coga",
    "Coronado": "coro",
    "Cowpens": "cowp",
    "Crater Lake": "crla",
    "Craters Of The Moon": "crmo",
    "Crossroads of the American Revolution": "xrds",
    "Cumberland Gap": "cuga",
    "Cumberland Island": "cuis",
    "Curecanti": "cure",
    "Cuyahoga Valley": "cuva",
    "David Berger": "dabe",
    "Dayton Aviation Heritage": "daav",
    "De Soto": "deso",
    "Death Valley": "deva",
    "Delaware & Lehigh": "dele",
    "Delaware Water Gap": "dewa",
    "Denali": "dena",
    "Devils Postpile": "depo",
    "Devils Tower": "deto",
    "Dinosaur": "dino",
    "Dry Tortugas": "drto",
    "Ebey's Landing": "ebla",
    "Edgar Allan Poe": "edal",
    "Effigy Mounds": "efmo",
    "Eisenhower": "eise",
    "El Camino Real de los Tejas": "elte",
    "El Camino Real de Tierra Adentro": "elca",
    "El Malpais": "elma",
    "El Morro": "elmo",
    "Eleanor Roosevelt": "elro",
    "Ellis Island": "elis",
    "Erie Canalway": "erie",
    "Essex": "esse",
    "Eugene O'Neill": "euon",
    "Everglades": "ever",
    "Fallen Timbers Battlefield and Fort Miamis": "fati",
    "Federal Hall": "feha",
    "Fire Island": "fiis",
    "First Ladies": "fila",
    "First State": "frst",
    "Flight 93": "flni",
    "Florissant Fossil Beds": "flfo",
    "Ford's Theatre": "foth",
    "Fort Bowie": "fobo",
    "Fort Davis": "foda",
    "Fort Donelson": "fodo",
    "Fort Dupont Park": "fodu",
    "Fort Foote": "fofo",
    "Fort Frederica": "fofr",
    "Fort Laramie": "fola",
    "Fort Larned": "fols",
    "Fort Matanzas": "foma",
    "Fort McHenry": "fomc",
    "Fort Monroe": "fomr",
    "Fort Necessity": "fone",
    "Fort Point": "fopo",
    "Fort Pulaski": "fopu",
    "Fort Raleigh": "fora",
    "Fort Scott": "fosc",
    "Fort Smith": "fosm",
    "Fort Stanwix": "fost",
    "Fort Sumter and Fort Moultrie": "fosu",
    "Fort Union": "foun",
    "Fort Union Trading Post": "fous",
    "Fort Vancouver": "fova",
    "Fort Washington": "fowa",
    "Fossil Butte": "fobu",
    "Franklin Delano Roosevelt Memorial": "frde",
    "Frederick Douglass": "frdo",
    "Frederick Law Olmsted": "frla",
    "Fredericksburg & Spotsylvania": "frsp",
    "Freedom Riders": "frri",
    "Friendship Hill": "frhi",
    "Gates Of The Arctic": "gaar",
    "Gateway Arch": "jeff",
    "Gateway": "gate",
    "Gauley River": "gari",
    "General Grant": "gegr",
    "George Rogers Clark": "gero",
    "George Washington Birthplace": "gewa",
    "George Washington Carver": "gwca",
    "George Washington": "gwmp",
    "Gettysburg": "gett",
    "Gila Cliff Dwellings": "gicl",
    "Glacier Bay": "glba",
    "Glacier": "glac",
    "Glen Canyon": "glca",
    "Glen Echo": "glec",
    "Gloria Dei Church": "glde",
    "Golden Gate": "goga",
    "Golden Spike": "gosp",
    "Governors Island": "gois",
    "Grand Canyon": "grca",
    "Grand Portage": "grpo",
    "Grand Teton": "grte",
    "Grant-Kohrs Ranch": "grko",
    "Great Basin": "grba",
    "Great Egg Harbor River": "greg",
    "Great Falls": "grfa",
    "Great Sand Dunes": "grsa",
    "Great Smoky Mountains": "grsm",
    "Green Springs": "grsp",
    "Greenbelt": "gree",
    "Guadalupe Mountains": "gumo",
    "Guilford Courthouse": "guco",
    "Gulf Islands": "guis",
    "Gullah/Geechee": "guge",
    "Hagerman Fossil Beds": "hafo",
    "Haleakalā;": "hale",
    "Hamilton Grange": "hagr",
    "Hampton": "hamp",
    "Harmony Hall": "haha",
    "Harpers Ferry": "hafe",
    "Harriet Tubman": "hart",
    "Harriet Tubman Underground Railroad": "hatu",
    "Harry S Truman": "hstr",
    "Hawaiʻi Volcanoes": "havo",
    "Herbert Hoover": "heho",
    "Historic Jamestowne": "jame",
    "Hohokam Pima": "pima",
    "Home Of Franklin D Roosevelt": "hofr",
    "Homestead": "home",
    "Honouliuli": "hono",
    "Hopewell Culture": "hocu",
    "Hopewell Furnace": "hofu",
    "Horseshoe Bend": "hobe",
    "Hot Springs": "hosp",
    "Hovenweep": "hove",
    "Hubbell Trading Post": "hutr",
    "Hudson River Valley": "hurv",
    "I&#241;upiat Heritage Center": "inup",
    "Ice Age Floods": "iafl",
    "Ice Age": "iatr",
    "Independence": "inde",
    "Indiana Dunes": "indu",
    "Isle Royale": "isro",
    "James A Garfield": "jaga",
    "Jean Lafitte": "jela",
    "Jewel Cave": "jeca",
    "Jimmy Carter": "jica",
    "John Day Fossil Beds": "joda",
    "John Fitzgerald Kennedy": "jofi",
    "John H. Chafee Blackstone River Valley": "blac",
    "John Muir": "jomu",
    "Johnstown Flood": "jofl",
    "Joshua Tree": "jotr",
    "Journey Through Hallowed Ground": "jthg",
    "Juan Bautista de Anza": "juba",
    "Kalaupapa": "kala",
    "Kaloko-Honok&#333;hau": "kaho",
    "Katahdin Woods and Waters": "kaww",
    "Katmai": "katm",
    "Kenai Fjords": "kefj",
    "Kenilworth Park & Aquatic Gardens": "keaq",
    "Kennesaw Mountain": "kemo",
    "Keweenaw": "kewe",
    "Kings Mountain": "kimo",
    "Klondike Gold Rush - Seattle Unit": "klse",
    "Klondike Gold Rush": "klgo",
    "Knife River Indian Villages": "knri",
    "Kobuk Valley": "kova",
    "Korean War Veterans Memorial": "kowa",
    "Lake Clark": "lacl",
    "Lake Mead": "lake",
    "Lake Meredith": "lamr",
    "Lake Roosevelt": "laro",
    "Lassen Volcanic": "lavo",
    "Lava Beds": "labe",
    "LBJ Memorial Grove on the Potomac": "lyba",
    "Lewis & Clark": "lecl",
    "Lewis and Clark": "lewi",
    "Lincoln Boyhood": "libo",
    "Lincoln Home": "liho",
    "Lincoln Memorial": "linc",
    "Little Bighorn Battlefield": "libi",
    "Little River Canyon": "liri",
    "Little Rock Central High School": "chsc",
    "Longfellow House Washington's Headquarters": "long",
    "Lowell": "lowe",
    "Lower Delaware": "lode",
    "Lower East Side Tenement Museum": "loea",
    "Lyndon B Johnson": "lyjo",
    "Maggie L Walker": "mawa",
    "Maine Acadian Culture": "maac",
    "Mammoth Cave": "maca",
    "Manassas": "mana",
    "Manhattan Project": "mapr",
    "Manzanar": "manz",
    "Marsh - Billings - Rockefeller": "mabi",
    "Martin Luther King, Jr. Memorial": "mlkm",
    "Martin Luther King, Jr.": "malu",
    "Martin Van Buren": "mava",
    "Mary McLeod Bethune Council House": "mamc",
    "Mesa Verde": "meve",
    "Minidoka": "miin",
    "Minute Man": "mima",
    "Minuteman Missile": "mimi",
    "Mississippi Delta": "mide",
    "Mississippi Gulf": "migu",
    "Mississippi Hills": "mihi",
    "Mississippi": "miss",
    "Missouri": "mnrr",
    "Mojave": "moja",
    "Monocacy": "mono",
    "Montezuma Castle": "moca",
    "Moores Creek": "mocr",
    "Mormon Pioneer": "mopi",
    "Morristown": "morr",
    "Motor Cities": "auto",
    "Mount Rainier": "mora",
    "Mount Rushmore": "moru",
    "Muir Woods": "muwo",
    "Muscle Shoals": "mush",
    "Natchez": "natc",
    "Natchez Trace": "natt",
    "Natchez Trace": "natr",
    "National Aviation": "avia",
    "National Capital Parks-East": "nace",
    "National Mall and Memorial Parks": "nama",
    "National Park of American Samoa": "npsa",
    "National Parks of New York Harbor": "npnh",
    "Natural Bridges": "nabr",
    "Navajo": "nava",
    "New Bedford Whaling": "nebe",
    "New England": "neen",
    "New Jersey Pinelands": "pine",
    "New Orleans Jazz": "jazz",
    "New River Gorge": "neri",
    "Nez Perce": "nepe",
    "Niagara Falls": "nifa",
    "Nicodemus": "nico",
    "Ninety Six": "nisi",
    "Niobrara": "niob",
    "Noatak": "noat",
    "North Cascades": "noca",
    "North Country": "noco",
    "Obed": "obed",
    "Ocmulgee Mounds": "ocmu",
    "Oil Region": "oire",
    "Oklahoma City": "okci",
    "Old Spanish": "olsp",
    "Olympic": "olym",
    "Oregon Caves": "orca",
    "Oregon": "oreg",
    "Organ Pipe Cactus": "orpi",
    "Overmountain Victory": "ovvi",
    "Oxon Cove  Park & Oxon Hill Farm": "oxhi",
    "Ozark": "ozar",
    "Padre Island": "pais",
    "Palo Alto Battlefield": "paal",
    "Parashant": "para",
    "Paterson Great Falls": "pagr",
    "Pea Ridge": "peri",
    "Pearl Harbor": "valr",
    "Pecos": "peco",
    "Pennsylvania Avenue": "paav",
    "Perry's Victory & International Peace": "pevi",
    "Petersburg": "pete",
    "Petrified Forest": "pefo",
    "Petroglyph": "petr",
    "Pictured Rocks": "piro",
    "Pinnacles": "pinn",
    "Pipe Spring": "pisp",
    "Pipestone": "pipe",
    "Piscataway": "pisc",
    "Point Reyes": "pore",
    "Pony Express": "poex",
    "Port Chicago Naval Magazine": "poch",
    "Potomac Heritage": "pohe",
    "Poverty Point": "popo",
    "President William Jefferson Clinton Birthplace Home": "wicl",
    "President's Park (White House)": "whho",
    "Presidio of San Francisco": "prsf",
    "Prince William Forest": "prwi",
    "Pu`uhonua O H&#333;naunau": "puho",
    "Pu`ukohol&#257; Heiau": "puhe",
    "Pullman": "pull",
    "Rainbow Bridge": "rabr",
    "Reconstruction Era": "reer",
    "Redwood": "redw",
    "Richmond": "rich",
    "Rio Grande": "rigr",
    "River Raisin": "rira",
    "Rivers Of Steel": "rist",
    "Rock Creek": "rocr",
    "Rocky Mountain": "romo",
    "Roger Williams": "rowi",
    "Roosevelt Campobello": "roca",
    "Rosie the Riveter WWII Home Front": "rori",
    "Russell Cave": "ruca",
    "Sagamore Hill": "sahi",
    "Saguaro": "sagu",
    "Saint Croix Island": "sacr",
    "Saint Croix": "sacn",
    "Saint Paul's Church": "sapa",
    "Saint-Gaudens": "saga",
    "Salem Maritime": "sama",
    "Salinas Pueblo Missions": "sapu",
    "Salt River Bay": "sari",
    "San Antonio Missions": "saan",
    "San Francisco Maritime": "safr",
    "San Juan Island": "sajh",
    "San Juan": "saju",
    "Sand Creek Massacre": "sand",
    "Santa Fe": "safe",
    "Santa Monica Mountains": "samo",
    "Saratoga": "sara",
    "Saugus Iron Works": "sair",
    "Schuylkill River Valley": "scrv",
    "Scotts Bluff": "scbl",
    "Selma To Montgomery": "semo",
    "Sequoia & Kings Canyon": "seki",
    "Shenandoah": "shen",
    "Shenandoah Valley Battlefields": "shvb",
    "Shiloh": "shil",
    "Sitka": "sitk",
    "Sleeping Bear Dunes": "slbe",
    "South Carolina": "soca",
    "Springfield Armory": "spar",
    "Star-Spangled Banner": "stsp",
    "Statue Of Liberty": "stli",
    "Steamtown": "stea",
    "Stones River": "stri",
    "Stonewall": "ston",
    "Sunset Crater Volcano": "sucr",
    "Tallgrass Prairie": "tapr",
    "Tennessee Civil War": "tecw",
    "Thaddeus Kosciuszko": "thko",
    "The Last Green Valley": "qush",
    "Theodore Roosevelt Birthplace": "thrb",
    "Theodore Roosevelt Inaugural": "thri",
    "Theodore Roosevelt Island": "this",
    "Theodore Roosevelt": "thro",
    "Thomas Cole": "thco",
    "Thomas Edison": "edis",
    "Thomas Jefferson Memorial": "thje",
    "Thomas Stone": "thst",
    "Timpanogos Cave": "tica",
    "Timucuan": "timu",
    "Tonto": "tont",
    "Touro Synagogue": "tosy",
    "Trail Of Tears": "trte",
    "Tule Lake": "tule",
    "Tule Springs Fossil Beds": "tusk",
    "Tumac\u00e1cori": "tuma",
    "Tupelo": "tupe",
    "Tuskegee Airmen": "tuai",
    "Tuskegee Institute": "tuin",
    "Tuzigoot": "tuzi",
    "Ulysses S Grant": "ulsg",
    "Upper Delaware": "upde",
    "Valles Caldera": "vall",
    "Valley Forge": "vafo",
    "Vanderbilt Mansion": "vama",
    "Vicksburg": "vick",
    "Vietnam Veterans": "vive",
    "Virgin Islands Coral Reef": "vicr",
    "Virgin Islands": "viis",
    "Voyageurs": "voya",
    "Waco Mammoth": "waco",
    "Walnut Canyon": "waca",
    "War In The Pacific": "wapa",
    "Washington Monument": "wamo",
    "Washington-Rochambeau Revolutionary Route": "waro",
    "Washita Battlefield": "waba",
    "Weir Farm": "wefa",
    "Wheeling": "whee",
    "Whiskeytown": "whis",
    "White Sands": "whsa",
    "Whitman Mission": "whmi",
    "William Howard Taft": "wiho",
    "Wilson's Creek": "wicr",
    "Wind Cave": "wica",
    "Wing Luke Museum": "wing",
    "Wolf Trap National Park for the Performing Arts": "wotr",
    "Women's Rights": "wori",
    "World War II Memorial": "wwii",
    "Wrangell - St. Elias": "wrst",
    "Wright Brothers": "wrbr",
    "Wupatki": "wupa",
    "Yellowstone": "yell",
    "Yorktown Battlefield": "york",
    "Yosemite": "yose",
    "Yucca House": "yuho",
    "Yukon - Charley Rivers": "yuch",
    "Zion": "zion"
}